### PR TITLE
Changes in templates.yml

### PR DESCRIPTION
**Pull request by caiobiodere**
Update original template version using framework7 v2 and framework7-vue v2 version

### CODE REVIEW

**Comment by caiobiodere** [comment]
I and Centrual appreciate the help and concern from Kevin :+1:

**Comment by nolimits4web** [comment]
And @kevinqqnj aware of it and doesn't mind about removing his template?

**Comment by kevinqqnj** [comment]
if new functions added, ok for me.

**Comment by caiobiodere** [comment]
@kevinqqnj Thanks :)

**Comment by caiobiodere** [comment]
@nolimits4web can you merge these changes?

**Pull request merged**
