### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by hazasaad**
My app code added in showcase

### CODE REVIEW

**Comment by nolimits4web** [comment]
I would request few changes before merging it:
* put your app on top of the list (in the beginning)
* lowercase image file names and no spaces in filenames
* looks like app title is wrong "iTasca – Tasca d’Almerita Wine and Estates"
* no empty lines in description section
```
description: |
      
           We provide you with the best experience in the field of construction
```
must be just 
```
description: |
  We provide you with the best experience in the field of construction
```

**Comment by hazasaad** [comment]
Is it ok or not ..

**Comment by hazasaad** [comment]
I solved all issues...

**Comment by nolimits4web** [comment]
Merged, thanks

**Comment by hazasaad** [comment]
thankz for ur concern

**Pull request merged**
