### PR TITLE
GoDial Showcase

### PR DESCRIPTION
**Pull request by theavijitsarkar**
Adding the app GoDial to Showcase

### CODE REVIEW

**Comment by nolimits4web** [comment]
Please, rename image files to the same naming convention as other showcase images have

**Comment by theavijitsarkar** [comment]
> Please, rename image files to the same naming convention as other showcase images have

Very sorry :P Have updated the naming conventions

**Comment by theavijitsarkar** [comment]
@nolimits4web Is this ok now?

**Comment by nolimits4web** [comment]
Merged, thanks!

**Comment by theavijitsarkar** [comment]
Thanks a lot!

**Pull request merged**
