### PR TITLE
Add Maple POS to Showcase

### PR DESCRIPTION
**Pull request by davykiash**

### CODE REVIEW

**Comment by nolimits4web** [comment]
Thanks, you need to put that images in `i/showcase/` folder and send with this PR

**Comment by davykiash** [comment]
I located a tutorial and managed to add the images to `i/showcase/` folder directly. Thanks.

**Comment by nolimits4web** [comment]
You should include them into PR (send commit with included images)

**Comment by davykiash** [comment]
Please advise if am on the right track with the images

git images

**Comment by davykiash** [comment]
Done.

**Comment by nolimits4web** [comment]
Merged, thanks!

**Pull request merged**
