### PR TITLE
adding Link by Rise to showcase

### PR DESCRIPTION
**Pull request by alexmillman2394**
Hi there,

We've added an app to the showcase. Please merge.

Thanks!

### CODE REVIEW

**Comment by nolimits4web** [comment]
Thanks 👍

**Comment by alexmillman2394** [comment]
Thank you!. I've noticed our images are 404ing. I committed them. Not sure if there's something else I had to do?

**Comment by alexmillman2394** [comment]
Never mind, it must have been a caching issue. viewed incognito and they're loading

**Comment by nolimits4web** [comment]
Oh, just noticed that you added it to the end, while it should be on the top (first). Can you send PR updating it?

**Comment by alexmillman2394** [comment]
Sorry about that. I will send a PR today

**Comment by alexmillman2394** [comment]
@nolimits4web sorry I'm late on this. I was just about to push when I noticed you already did it yourself.

Thank you sir

**Pull request merged**
