### PR TITLE
fix horizontal scrollbar

### PR DESCRIPTION
**Pull request by Arhell**

### CODE REVIEW

**Comment by nolimits4web** [comment]
Sorry, but it will break site usability on screens with < 800px width

**Comment by nolimits4web** [comment]
Where is exactly do you see that unnecessary scrolling?

**Comment by Arhell** [comment]
Hi, http://joxi.ru/BA0Qqv1TJ3j0qr
.home-featured:before
Maybe just rewrite this block?
Chrome on mac mini

**Comment by Arhell** [comment]
Hello, how about that suggestion?
last commit 'next suggestion'

**Comment by nolimits4web** [comment]
Ok, closing as not actual anymore

**Pull request closed without merging**
